-- 테이블 생성
CREATE TABLE tb_board_participation_list(
	  particip_no			NUMBER 			CONSTRAINT PK_TB_INVITATION_LIST_INV_NO PRIMARY KEY
	, emp_id				VARCHAR2(30)	CONSTRAINT FK_TB_INVITATION_LIST_EMP_ID REFERENCES TB_EMPLOYEES(EMP_ID)
	, board_id				NUMBER			CONSTRAINT FK_TB_INVITATION_LIST_BOARD_ID REFERENCES TB_BOARDS(BOARD_ID)
);

-- 시퀀스 생성 
CREATE SEQUENCE board_particip_seq NOCACHE;

-- 값넣기
INSERT INTO TB_BOARD_PARTICIPATION_LIST VALUES(board_particip_seq.NEXTVAL,'A2022116',7);
INSERT INTO TB_BOARD_PARTICIPATION_LIST VALUES(board_particip_seq.NEXTVAL,'A2022115',7);
INSERT INTO TB_BOARD_PARTICIPATION_LIST VALUES(board_particip_seq.NEXTVAL,'A2022108',7);
INSERT INTO TB_BOARD_PARTICIPATION_LIST VALUES(board_particip_seq.NEXTVAL,'A2022101',7);
INSERT INTO TB_BOARD_PARTICIPATION_LIST VALUES(board_particip_seq.NEXTVAL,'A2022100',7);
INSERT INTO TB_BOARD_PARTICIPATION_LIST VALUES(board_particip_seq.NEXTVAL,'A2022102',7);
INSERT INTO TB_BOARD_PARTICIPATION_LIST VALUES(board_particip_seq.NEXTVAL,'A2022103',7);
INSERT INTO TB_BOARD_PARTICIPATION_LIST VALUES(board_particip_seq.NEXTVAL,'A2022104',7);